---
title: "Rescaling groundfish projected catch to meet the GOA OY cap"
author: "Alberto Rovellini"
date: "February 27, 2025"
format: docx
---

This approach takes a vector of projected catch $ABC$ for a set of stocks and applies a series of rescaling steps to transform it into a vector $ABC_{final}$ such that, given an ecosystem cap on total harvest $OY_{cap}$, the following conditions are satisfied for each stock $i$:

1.  $\sum_{i=1}^n ABC_{final,i}\leq OY_{cap}$
2.  $ABC_{final,i} = min(ABC_i, ABC_{final,i})$
3.  If $ABC_i > 0$, then $ABC_{final,i} > 0$

The input needed for the rescaling is a set of weights $w$. The approach laid out here assumes that high-value stocks will have higher $w_i$ and will undergo lower rescaling. Previous versions of this approach calculated the $ABC$ in excess of the OY cap and assigned it as deductions to $ABC_i$ each stock $i$ based on the weights. However, that approach often led to zero-catch for some of the low-value stocks, which is undesirable due to by-catch considerations. The approach presented here strives to work as much as possible in proportional space instead of with raw catch.

To meet all conditions above at once, the rescaling is done over several steps where a series of reduction factors and stock-specific scaling factors are computed. Reduction factors relate the aggregate $ABC$ to the ecosystem cap. Stock-specific scaling factors rescale $ABC_i$ for each stock $i$ using the weights.

The vector of weights $w$ is used in two ways in this approach. First, in a power function to apply the first rescaling. Then, standardized relative to $max(w)$ for further rescaling.

A Shiny App illustrating this approach is available [here](https://swzlz7-alberto-rovellini.shinyapps.io/oy_rescaling_app/).

Here are the steps:

1.  Calculate the first reduction factor $r_1$: $$r_1 = \frac{OY_{cap}}{\sum_{i=1}^n ABC_i}$$

This calculates the initial reduction factor based on the ratio of the cap to the sum of all projected catches (i.e., how much in excess of the cap are we?).

2.  Calculate the first scaling factor $s_1$:

$$
s_{1,i} = r_1^{(1/w_i)}
$$

This scalar will preserve the catch values for high-value stocks by applying a weighted power transformation.

3.  Perform the first catch adjustment: $$ABC_{1,i} = ABC_i \times s_{1,i}$$

At this point we may still be in excess of the OY cap.

4.  Calculate the second reduction factor $r_2$: $$r_2 = \frac{OY_{cap}}{\sum_{i=1}^n ABC_{1,i}}$$

This determines how much further adjustment is still needed after the first adjustment.

5.  Calculate the second scaling factor $s_2$. First, scale the weights to 0-1 range: $$w_{n,i} = \frac{w_i}{\max(w_1, w_2, \ldots, w_n)}$$

This standardizes the weights relative to the maximum weight value. It is done so that the most valuable stock has a weight of 1. Then compute $s_2$: $$s_{2,i} = w_{n,i} + (1 - w_{n,i}) \times r_2$$

This creates a stock-specific scaling factor as a weighted combination of 1 and the second reduction factor $r_2$. For the highest-value stock, this ensures minimal rescaling (though we still need to comply with $r_2$).

6.  Perform the second catch adjustment: $$ABC_{2,i} = ABC_{1,i} \times s_{2,i}$$

Note that $ABC_2$ is an intermediate quantity used to compute the third and final reduction factor.

7.  Calculate the third reduction factor $r_3$ and scaling factor $s_3$: $$r_3 = \frac{OY_{cap}}{\sum_{i=1}^n ABC_{2,i}}$$ $$s_{3,i} = s_{2,i} \times r_3$$

This will ensure that the total catch remains under the cap after the previous adjustments by performing stock-specific adjustments.

8.  Perform the third catch adjustment: $$ABC_{3,i} = ABC_{1,i} \times s_{3,i}$$
9.  At this point the aggregate $ABC_3$ should be at the cap. However, one remaining issue for some combinations of $w$ (and depending on stock status) is that the previous steps may have caused some upscaling of the original $ABC$ values. This would be a violation of the single-species catch allocation step that precedes the OY rescaling (particularly problematic for stocks that are managed with an HCR). This step constrains the projected catch to not exceed original $ABC$. We also need to keep track of any leftover unallocated catch $E$ that may results from deducting the $ABC$ in excess in this step:

$$E = \sum_{i=1}^n (ABC_{3,i} - ABC_i) \text{ where } ABC_{3,i} > ABC_i$$

$$ABC_{4,i} = \min(ABC_{3,i}, ABC_i)$$

At this point, if $E = 0$, then $ABC_{final} = ABC_4$.

10. **This last step is only executed if the previous steps have led to** $E>0$**.** Redistribute $E$ among the other stocks based on their original $ABC$ (i.e., stocks that had larger $ABC$ to absorb more of the excess): $$w_{resid,i} = \frac{ABC_i - ABC_{4,i}}{\sum_{j=1}^n (ABC_j - ABC_{4,j})}$$

Note that for stocks where $ABC_{4,i} = ABC_i$ due to step 9, $w_{resid,i}=0$. This is to avoid reassigning any part of excess to stocks that are already meeting their single-species catch allocation.

$$ABC_{final,i} = ABC_{4,i} + w_{resid,i} \times E$$
